---
- hosts: [es-nodes]
  remote_user: root
  roles:
    - basic-ubuntu
    - oracle-java
    - elastic
  vars:
    private_network_interface: ansible_eth1
  vars_files:
    - secrets.yml
  tags:
    - elastic
- hosts: [proxy]
  remote_user: root
  roles:
    - proxy
  vars:
    private_network_interface: ansible_eth1
  vars_files:
    - secrets.yml
  tags:
    - proxy
