---
- hosts: [es-nodes]
  remote_user: root
  roles:
    - basic-ubuntu
    - oracle-java
    - elastic
  tags:
    - elastic
- hosts: [proxy]
  remote_user: root
  roles:
    - proxy
  tags:
    - haproxy
