---
  - name: Install Oracle Java Repo Installer Repository
    apt_repository: repo=ppa:webupd8team/java update-cache=yes 

  - name: Wizardry to bypass the Oracle License File prompt
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

  - name: Install Oracle Java 6
    apt: pkg=oracle-java6-installer
    when: oracle_java_version == 6

  - name: Install Oracle Java 7
    apt: pkg=oracle-java7-installer
    when: oracle_java_version == 7

  - name: Install Oracle Java 8
    apt: pkg=oracle-java8-installer
    when: oracle_java_version == 8
