---
- name: Generate elasticsearch.yml config
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644
  notify: Restart elasticsearch

- name: Generate elasticsearch service config
  template: src=elasticsearch.default.j2 dest=/etc/default/elasticsearch owner=elasticsearch group=elasticsearch mode=0644
  notify: Restart elasticsearch

- name: Enable elasticsearch
  service: name=elasticsearch enabled=yes state=started

- name: Open ports for intenal cluster communication
  ufw: rule=allow port=9300 proto=tcp src="{{ hostvars[item][private_network_interface]['ipv4']['address'] }}"
  with_items:
    - "{{ groups['es-nodes'] }}"
