---
- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- name: Install Server Basics
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - unattended-upgrades
    - ntp
    - wget
    - curl
    - vim
    - ack-grep
    - git
    - unzip
    - htop
    - tmux
    - ufw
  notify:
    - Start NTP

- name: Add Periodic Configuration
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: Add Unattended Upgrade Configuration
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
  notify:
   - Restart Unattended Upgrades

- name: Disable Incoming Traffic
  ufw: policy=deny direction=incoming
  notify: Reload ufw

- name: Enable Outgoing Traffic 
  ufw: policy=allow direction=outgoing
  notify: Reload ufw

- name: Enable all incoming from localhost
  ufw: rule=allow src=127.0.0.1
  notify: Reload ufw

- name: Enable SSH
  ufw: rule=allow name=OpenSSH
  notify: Reload ufw

- name: Rate Limit SSH
  ufw: rule=limit name=OpenSSH
  notify: Reload ufw

- name: Start Ufw
  ufw: state=enabled
