---
- name: Generate elasticsearch.yml config
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner=elastic group=elastic mode=0644
  notify: Restart elasticsearch

- name: Generate elasticsearch service config
  template: src=elasticsearch.default.j2 dest=/etc/default/elasticsearch owner=elastic group=elastic mode=0644
  notify: Restart elasticsearch
