---
- name: Add Elastic Group
  group: name=elastic state=present

- name: Add Elastic User
  user: name=elastic group=elastic

- name: Set User Limits
  copy: src=limits.conf dest=/etc/security/limits.conf owner=root group=root

- name: Set Pam.d to Accept User Limits
  lineinfile:
    line="session required pam_limits.so"
    dest=/etc/pam.d/common-session
    regexp="session required pam_limits.so"
    insertafter="^# end of pam-auth-update config"


- name: Check Elasticsearch Installed
  shell: if [ -e /usr/share/elasticsearch/lib/elasticsearch-{{ elasticsearch_version }}.jar ]; then echo yes; else echo no; fi;
  register: version_exists
  always_run: True

- name: Download Elasticsearch deb
  get_url: url={{ elasticsearch_download_url }}/elasticsearch-{{ elasticsearch_version }}.deb dest=/tmp/elasticsearch-{{ elasticsearch_version }}.deb mode=0440
  when: version_exists.stdout == 'no'

- name: Uninstalling previous version if applicable
  shell: dpkg --remove elasticsearch
  when: version_exists.stdout == 'no'
- file: path=/usr/share/elasticsearch state=absent
  when: version_exists.stdout == 'no'

- name: Install Elasticsearch deb
  shell: dpkg -i -E --force-confnew /tmp/elasticsearch-{{ elasticsearch_version }}.deb
  when: version_exists.stdout == 'no'
- file: path=/usr/share/elasticsearch state=directory owner=elastic group=elastic recurse=yes
  
- name: Configuring directories
  file: path={{ elasticsearch_log_dir }} state=directory owner=elastic group=elastic recurse=yes
  when: elasticsearch_log_dir is defined
- file: path={{ elasticsearch_data_dir }} state=directory owner=elastic group=elastic recurse=yes
  when: elasticsearch_data_dir is defined
- file: path={{ elasticsearch_work_dir }} state=directory owner=elastic group=elastic recurse=yes
  when: elasticsearch_work_dir is defined
- file: path={{ elasticsearch_conf_dir }} state=directory owner=elastic group=elastic recurse=yes
  when: elasticsearch_conf_dir is defined
- file: path={{ elasticsearch_plugin_dir }} state=absent
  when: elasticsearch_plugin_dir is defined
- file: path={{ elasticsearch_plugin_dir }} state=directory owner=elastic group=elastic recurse=yes
  when: elasticsearch_plugin_dir is defined

- name: Configuring Elasticsearch Node
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner=elastic group=elastic mode=0644
  when: elasticsearch_conf_dir is defined
  notify: Restart Elasticsearch

- template: src=elasticsearch.default.j2 dest=/etc/default/elasticsearch owner=elastic group=elastic mode=0644
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch is started on boot
  service: name=elasticsearch enabled=yes state=started
